package com.example.juegosdejere3

object QuestionsData {
    val sectorQuestions = mutableMapOf(
        "¿Quien?" to mapOf(
            "GRUPO A" to listOf(
                "“Que pesen 60kg ya me parecen gordas”" to "Santi",
                "“No puede ser amigo, me hice un tinder y todas las minas que me dan like están arriba de los 60kg, deberían hacer un tinder antigordas, si pesan más de 60kg no tendrían que poder hacerse la cuenta”" to "Juli",
                "“Exigis exigis y te estas quedando pelado, vas a tener que bajar la vara”" to "Mati a Juli",
                "“Estoy leyendo la biblia de nuevo, que joyita literaria”" to "Mati",
                "“Yo a una Judía me la garcho y la hago Argentina”" to "Mati, tiene una pija peronizadora",
                "“Las mucamas son todas bolitas, te cogiste una bolita”" to "Juli",
                "“Hice el amor en el hospital con una mucama”" to "Gonza",
                "“Se me complicó cogerme a la gorda, no veía un culo”" to "Juli",
                "“Vos te la tenés que coger bien, dejarle la concha doliendo”" to "Gonza",
                "“Mi salvación de acá a 5 años es que se muera mi abuela”" to "Juli",
                "“No todo es plata”" to "Juli",
                "“Viedma está lleno de negras pobres”" to "Gonza",
                "“La atracción por los culos viene del sexo desde atrás, forma de relación sexual heredada de los hominidos y replicada por los bonobos o chimpancés. La atracción por las tetas viene de la reproducción sexual frente-frente y la romantización del sexo, caracteristica de los humanos. A mi me gusta garchar mirando a los ojos”" to "Mati",
                "“si una “amiga” me encara y es fea hago como que me importa la amistad”" to "Mati",
                "“Tinder es peor que las apuestas, en las apuestas al menos ganas a veces, acá todas gordas”" to "Juli",
                "“Si queres ver tetas anda a ver airbag y listo, no te anotes en una campaña de cáncer de mama”" to "Gonza a Juli",
                "“Pobre mi abuelita, le robe el celular”" to "Santi",
                "“Parezco una vieja con el pelo así”" to "Enzo",
                "“Me parece que tengo parasitos, me pica el culo y me meto el dedo”" to "Gonza",
                "“Mis requisitos en el porno es que sea casero, argentino y con buen audio, sino no me calienta”" to "Mati",
                "“Casi le chupo todo el culo a Enzo”" to "Mati",
                "“¿Y si Lio murió y el evento fue tan traumático que todos creemos que está vivo y no lo dejamos ir?”" to "Enzo (Problabemente pasado de estupefacientes)",
                "“Cuando las ganas aparecen no se puede hacer nada, hoy me voy a tocar con una coreana”" to "Jere",
                "“Yo el día que tenga una novia va a ser la madre de mis hijos”" to "Mati",
                "“En turquía te devuelve el pelo por 2000 dólares”" to "Mati",
                "“Me siento como si me hubiera garchado a una minusa qué está re buena pero no acabe”" to "Mati despues del empate con el benfica",
                "“Cuando tenga 75 años y tenga un enfermedad terminal voy a ir a la bombonera por última vez y voy a llevarme a un jugador de fútbol conmigo”" to "Mati",
                "“Si yo fuera gay, Enzo sería bastante mi típo, por la nariz, la altura y el tipo de cuerpo”" to "Jere",
                "“He visto uno que otro hentai”" to "Mati",
                "“Yo ví bastante hentai pero me parece raro, igual acabe con unos pares”" to "Juli",
                "“Yo cuando tenía 20 estuve con una de 17 y no paso nada”" to "Juli",
                "“Desde hace 3 meses que me estoy poniendo un producto para que me crezca el pelo y así no quedarme pelado”" to "Juli",
                "“Quiero que me chupen la pija, no me importa si es hombre o mujer”" to "Juli",
                "“Más bien que le miro las tetas a un traba, se las chupo si es necesario”" to "Gonza",
                "“Yo no sé si no soy medio autista”" to "Mati",
                "“Amigo deja de calentarme, estoy en el medio del hospital por hacerme una radiografía con el choto en alza”" to "Jere",
                "“Tiene terrible voz de pito pero tiene una cola terrible la hdp”" to "Santi",
                "“Te voy a chupetear el puentecito y acabes con tanta potencia que le caiga a dionisio (el gato de Enzo) en el tazón de agua”" to "Jere a Mati",
                "“Yo no ví el vídeo de la pija de Icardi por miedo a sentirme mal”" to "Mati",
                "“Si tuviera micropene me haría puto y me dejaría romper el orto”" to "Gonza (Nomas se quiere hacer romper el orto)",
                "“Yo no me puedo olvidar de tu ex”" to "Juli",
                "“Cuando le saque la remera pensé que era trans y que me iba a encontrar con un micropene, tenía el cuerpo de un hombre”" to "Santi",
                "“Había una gorda, no sabes lo que era, un chancho”" to "Enzo",
                "“Después de la paja me dan ganas de comer algo y escuchar música”" to "Mati",
                "Pueden creer q trabaje con un trans, Y no me di cuenta hasta hoy" to "Juli",
                "“Es lo mismo pajearse que coger o que ponersela a tu perro”" to "Jere",
                "Yo no tengo enanos trabajando para mí, aunque sería una buena idea" to "Mati",
                "Tendría que haberle escupido a un nene en la cara, así no me llamaban a laburar de nuevo" to "Jere",
                "“¿Que haces si viene un amigo tuyo, te dice que quiere tomar unos mates y de la nada te dice que quiere probar con los hombres?”" to "Jere",
                "“Yo reacciono mal si viene Juli, me dice que es gay y me toca la pierna”" to "Mati",
                "“Dios te oiga amigo, es lo único que quiero en esta vida, una relación abiertamente homosexual con Enzo”" to "Jere",
                "“Por dos palitos me dejó dedear un rato el orto”" to "Enzo",
                "“Por ahí me lo cojo al transexual ese y fue”" to "Juli",
                "“Ya puedo decir oficialmente que le lustre los huevos con la lengua a un modelo”" to "Jere (En referencia a Mati)",
                "“Yo con los de mi secundaria nos mediamos el pitulin, yo estaba ahí en el medio”" to "Gonza",
                "“Hoy me hice la paja con una parodia porno del exorcista, una de las mejores pajas de mi vida”" to "Jere"
            ),
            "GRUPO B" to listOf(
                "“Imaginate un mundo donde pudiéramos hacer lo que quieras, voy y mato a alguien”" to "Leo",
                "“Me llegan a pasar una pija mientras estoy cagando y se la pinchó con una lapicera”" to "Leo",
                "“Quiero hacerle torsión testicular a un pelado”" to "Ema",
                "“Mi único morbo son las embarazadas porque un tipo estuvo ahí recientemente”" to "Leo",
                "“La paja siempre empieza en Instagram”" to "-Jere 2025",
                "“Dame un beso en el culo a ver si es lo mismo que la boca”" to "Josué a Iván",
                "“El 90% de las mujeres tienen algún problema psicológico”" to "Leo",
                "“No sé cómo son las minas, solo trato con hombres”" to "Ema",
                "“Uff, la amiga de mi novia tiene un culo así de grande”" to "Josué (Asi se ven 8 años de relacion)",
                "“Voy a hacer la de lio con tu hermana si se queda embarazada”" to "Jere a Leo",
                "“La edad de consentimiento en realidad es de 13 si no te denuncia”" to "Ema (Es un enfermo)",
                "“Quiero vivir lo que es cuidar a un cuadripléjico”" to "Leo",
                "“Soñé que Ema tenía tetas, y un poco me gustó”" to "Leo",
                "“Quiero romper un himen”" to "Ema",
                "“Porno y cosas sobrenaturales son mis dos temas favoritos, y he visto videos que los combinan”" to "Jere",
                "“Dios te va a castigar con trillizos down”" to "Leo a Josué",
                "“Ver downs le produce tanta dopamina que su cerebro dijo, ¿y si hacemos a nuestra descendencia down?, una tanda le sale con down y otra con enanismo”" to "Ema",
                "“Si tengo un amigo que se hace gay no dejaría ni que me toque, mucho menos acostarnos juntos”" to "Josué (Según el no es homofobico, sino coherente)",
                "“Vos te mereces que tú novia se ponga gorda, obesa, redonda”" to "Leo a Josué",
                "“Da ganas de violarla”" to "Leo",
                "“Si sos gorda no tengas los estándares tan altos, no podés esperar algo bueno”" to "Leo",
                "“me están empezando a salir videos en ig de hombres en tanga y de trabas”" to "Leo",
                "“No pagarían por culear ustedes? Yo si pagaría”" to "Josué",
                "“Para mí los gordos y las gordas no tendrían que existir”" to "Iván",
                "“Pero mostra las tetas pedazo de puta”" to "Iván",
                "“Si te sale down es un buen motivo de aborto”" to "Iván",
                "“No quiero ser el que le ponga fin a su relación, eso se le dejó a alguna alumna o a algun negro brasilero”" to "Jere a Iván",
                "“La hija de leo va a estar tremenda”" to "Ema (Apuesto 1000 dolares a que todos dijeron Jere xd, tambien pienso que va a estar tremenda igual)",
                "“Cómo que Dios no castiga dos veces, mira los futuros hijos de Josué, negros y downs”" to "Jere",
                "“Si yo pido una mina que no salga todos los findes y que no haya estado con muchos pibes probablemente sea una re gorda, redonda”" to "Leo",
                "“Mientras vos bajas el auto ella baja para chuparle la pija a otro”" to "Ema (El mas tranquilo del grupo segun dicen)",
                "“Yo la verdad que haría un cuarteto con un amigo pero nomás si los dos tenemos novia y nos miramos a los ojos mientras lo hacemos”" to "Jere",
                "“La gente que sobrevio al holocausto tenia un factor comun que era que tenian algo pendiente por hacer, eso era morir”" to "Josue (Lo banco)",
                "“Ya va a llegar una adicta a vos que pasó por todas las vergas del mundo, pero va a llegar”" to "Iván a Ema (No va a llegar un carajo)",
                "“Pero la cajeta de la novia (de josué) ya no sirve y te tiene q pasar la manutención”" to "Leo",
                "“Eso es lo q pasa cuando una mina tiene un pibe, le queda como una cacerola la concha”" to "Leo (No tiene ningún respeto por las mujeres)",
                "“No se si es una niña, ojala que no, no sería conveniente”" to "Leo",
                "“Yo tuve una fantasía en las duchas de natación con tu abuela”" to "Leo a Jere",
                "“Ojala morir así, atravesado por un cuchillo mientras me estoy cogiendo una esquizofrénica”" to "Jere",
                "“Yo si un día me levanto y soy mujer obvio que me metería los dedos”" to "Leo",
                "“La hermana de Iván envejeció como un buen vino”" to "Ema",
                "“El amor tiene que ser duro y tóxico, cada tanto pegarle a tu pareja no está tan mal”" to "Leo (Va a terminar preso antes de los 30)",
                "“Me voy a dejar el pelo largo, comprar ropa y garcharme a todas mis alumnas, menos a las gordas y feas”" to "Iván",
                "“¿Pero qué querés, ver a tu hija chapando con su novia mientras vos te pajeas hdp?”" to "Leo a Iván",
                "“Si ... no me dejaba cogermela yo igual me la violaba”" to "Leo",
                "“No sé si ema está en todos lados, pero en la cama con tu novia seguro que si”" to "Leo a Iván (Ahí estaba seguro)",
                "“Yo no le chuparia la concha a una negra, meterle los dedos y coger si, pero me da a qué tiene mal olor”" to "Jere",
                "“La paja con los pies es lo mejor del mundo”" to "Jere",
                "“No me imagino una sin culo, no podes agarrar ni ver nada, es como garchar con un escobillón”" to "Josué (Creo que le gustan los culos)",
                "“Tal vez solo hay q amar a las personas y no a su género”" to "Leo",
                "“Eso son las mujeres, caras bonitas y culos grandes, no tienen una de las dos y ya no son mujeres”" to "Iván (No se como chota tiene una relacion de 6 años este tipo)",
                "“Dejen de juzgar cuerpos ajenos”" to "Leo",
                "“Antes de ir a la guerra a defender judíos me suicidó, prefiero defender violadores”" to "Jere (No me arrepiento una mierda de lo que dije, lo sostengo)",
                "“Porque en el fondo sos un toca nenes, pelado pajín”" to "Ema a Iván",
                "“El condón femenino es para putos, si vas a chupar una buena concha arriesgate un poco a contraer una ETS, sino ni la chupes”" to "Jere",
                "“Cómo vas a ser un hombre de color y no chupar concha, es como si un chino no comiera arroz”" to "Jere",
                "“¿Y si te comes una pija mientras yo miro?”" to "Leo a Jere",
                "“Ese sí sería un buen femicidio”" to "Leo",
                "“Prefiero defender a un nazi que a un judio”" to "Josué",
                "“Una vez encontré una actriz porno muy parecida a tu hermana”" to "Leo a Iván",
                "“Lo mejor es acabarse en el calzoncillo y después ponerlo a lavar”" to "Leo",
                "“Una vez me hice 6 pajas en un día con revistas porno”" to "Josué",
                "“Si le tengo mucho amor si dejaría que me meta el dedo o chuparle el culo si ella me lo pide”" to "Jere",
                "“Yo tengo miedo de si tomo viagra se me explote la pija”" to "Josué",
                "“Yo tenía ganas de probar el viagra a ver qué onda”" to "Iván",
                "“Igual yo me la violaria antes de matarla, obviamente, si ya estoy en el baile”" to "Leo ",
                "“Cómo me calienta la división oncológica”" to "Ema",
                "“Ser discapacitado no es una elección, elegir una carrera de discapacitado si lo es”" to "Josué",
                "“Es como que un down tenga de amigo a una persona con autismo”" to "Josué",
                "“En realidad los jdj se tendrían que llamar ‘que mierda hay en la mente de un violador, secuestrador y asesino osea la mente de Leo’”" to "Josue (Y tiene razon)",
                "“Esas personas no tienen papás, tiene que venir alguien y arruinarlas, cosa que el suicidio sea la única manera de tener éxito en algo en sus mediocres vidas“" to "Josué",
                "“Tendrían que llevar a los autistas a la guerra, mira si son rambo, que así paguen su fianza en el planeta tierra”" to "Josue",
                "“Yo no me sentiría tan mal si mi novia me caga con una mujer”" to "Leo",
                "“Elegiría siempre a Dios porque Dios es todo”" to "Ema",
                "“Si un down pudo conseguir laburo seguro vos también podés”" to "Josué a Jere",
                "“La mina puede ser alto lechón y no pasa nada”" to "Leo",
                "“El promedio de inteligencia no es el mismo que el promedio de inteligencia de una mina”" to "Ema",
                "“¿Que tiene de malo ver una historia de amor entre dos hombres? Yo lo hice”" to "Leo (¿La habra visto o la habra vivido?)",
                "“Ya mucho que te aguantaste cuando te meti el dedito, el punto G de los hombres está ahí“" to "Jere",
                "“Ojala tener la despedida, pero de la vida de algunos de ustedes”" to "Josué",
                "“Yo si estaría con una vieja vieja por plata, lo único que sí me costaría bajar y en menor medida dar cariño”" to "Leo",
                "“Me muerde una oreja y explotó en leche”" to "Leo",
                "“Las contratan porque son terribles putas claramente, no porque tengan un título universitario”" to "Josué",
                "“Esas se hacen las feministas pero están esperando que alguien venga y le diga te rompo el ogt”" to "Josué (Habia tomado una birra nomas)",
                "“No puedo ver un vídeo porno sin una pija”" to "Jere",
                "“El culo de tu mamá estudió amigo, no ves que está lleno de pelotudeces?“" to "Iván a Josué",
                "“Ni a palo gasto eso con esa gordita, tenes ganas de tomar algo? Tomate mi leche y dejame de romper las pelotas”" to "Josué",
                "“Tu pensamiento atrasa, no podés decir que una mina es puta”" to "Leo (Un hombre de principios)",
                "“En Etiopía, el chabon con más vacas se queda a la minita“" to "Leo",
                "“Si me pide tener unos terrenos para levantarmela, mínimo q le salgan fuegos artificiales de la concha“" to "Leo",
                "“¿Alguna vez tu jermu te hizo un pete en el cine?”" to "Jere a Ivan",
                "“Cuando a tu novia no le baja por 3 meses y vos estas sentadito ahí en la cama esperando a que salga del baño con la prueba de embarazo, eso da miedo”" to "Jere",
                "“¿A tu hermana alguna vez se la trataron de violar?”" to "Jere a Iván",
                "“God que sea menor, la terminás de criar vos, la vas manipulando para que crea que están bien cosas que están para el orto. Para que piense que el estándar es cagarla a trompadas, que te haga petes y te cocine, que piense que siempre tenés razón”" to "Iván (Miralo al profe)",
                "“Ofrezco escuchar tus pensamientos, mientras me manoseo la rata”" to "Leo",
                "“Cómo vas a coger a una negra a pelo, jamás, tienen enfermedades”" to "Jere",
                "“Lo máximo que ví un vídeo porno fue 15 veces”" to "Leo (Y dijo que no era tanto)",
                "“Yo me dejo meter un dedo en el orto si después me hace una turca”" to "Ema",
                "“Me decís que tú novia está en tu casa y voy y te violo en frente de ella“" to "Iván a Josué",
                "“Y si, no te queda otra que violarla no?”" to "Ema",
                "“Agradezcanle a sus viejas que se dejaron acabar adentro”" to "Josué",
                "“Le dibujo una sonrisa con mi leche al cadáver”" to "Leo",
                "“Puta cara (en referencia a la novia de Josué)”" to "Leo",
                "“Tengo una alumna que me hace ojitos, está para detonarla”" to "Iván (sus alumnas tenian 17/18 años)"

        ),
            "GRUPO C" to listOf(
                "“¿Tan raro es que me vean hablando con mujeres?”" to "Pablo",
                "“Tendrías que ser más simpático”" to "Gusti a Iván",
                "“Que lindo arito, te combina con el pelo”" to "Pablo",
                "“Me gusta dura y venosa”" to "Iván",
                "“Se ve que chupe muchas pijas, tengo la garganta hecha concha”" to "Jere",
                "“Es culpa mía porque me gustan las pijas grandes”" to "Joaco",
                "“Silvia es terrible nombre de puta”" to "Iván (Su mama se llama Silvia xd)",
                "“Ir al proctologo es más barato que ir a buscar trabas”" to "Pablo",
                "“Soy catolico, por eso odio a gusti, por mujer y por homosexual”" to "Pablo (Que hombre)",
                "“Si la remera no tiene una pija con sífilis eyaculando te parece básica hdp”" to "Jere a Iván",
                "“Vos porque querés buscar minitas de 15 pedazo de pedofilo”" to "Jere a Iván",
                "“Y si los objetos son las mujeres”" to "Pablo",
                "“Ya quisieras que te esté cogiendo”" to "Pablo a Iván",
                "“Un caminante se hace de los caminos que camino”" to "Pablo",
                "“¿Vos no escuchas eso? Las voces que dicen que mates a toda tu familia”" to "Pablo",
                "“Estoy del lado de Pablo porque es hombre”" to "Jere",
                "“Si yo me hubiese cruzado de calle cada vez que veía un negro en la vereda nunca me habrían robado”" to "Pablo",
                "“Ese lo hice a pelo”" to "Pablo",
                "“Yo saldría con tu hermana solo por tenerte de cuñado”" to "Pablo",
                "“Yo quiero que todo sea lo más rápido posible, que termine todo rápido”" to "Gusti",
                "“Bueno hubiese sido si te ponía las dos cabezas de enano que tiene por tetas en la cara”" to "Jere a Gusti",
                "“Vos por las dudas tenés que ser infiel”" to "Achi a Iván",
                "“Todos deberíamos tener un hijo preventivo con otra mujer”" to "Achi",
                "“Si no lo impedis es que lo estabas buscando”" to "Achi",
                "“Encima es bisexual, seguro le están dando entre 4”" to "Gusti",
                "“Lo importante es que es tu verga”" to "Gusti a Pablo",
                "“Cagate la vida por alguien que esté buena al menos”" to "Jere",
                "“A los campeones del mundo se los tendría que exhonerar”" to "Achi",
                "“Si Montiel es un violador yo me paro y lo aplaudo, es campeón del mundo”" to "Jere",
                "“Yo también tengo cositas de violador”" to "Iván",
                "“La paradoja más grande que vi en mi vida, y eso que le vi el miembro viril a Pablo”" to "Jere",
                "“A mí me calienta el grooming”" to "Jere",
                "“Tuve una novia pero se suicidó”" to "Achi",
                "“Cuando a una mujer la violan es claramente su culpa, podría pegarle una patada en los huevos y listo”" to "Iván",
                "“Estamos criticando formas de vida inferiores, como los chinos, los judios y los monos”" to "Iván",
                "“Cómo me gusta el artículo 19 de la constitución”" to "Pablo",
                "“Imagínate que tu hija venga y te diga que tiene un novio de punta alta, me mato”" to "Pablo",
                "“El culo de esa mina es un milagro de la vida”" to "Jere",
                "“Lo drogas y te lo empomas”" to "Jere",

                )
        ),
        "Pitonari" to mapOf(
            "GRUPO A" to listOf(
                "A1" to "El brazo de costas",
                "A2" to "Borja rezando",
                "A3" to "Enzo y Jere casandose (Jere con vestido, Enzo con traje)",
                "A4" to "Juli con la gorda de la copa américa",
                "A5" to "Gonza midiendose el pito en el baño de su escuela",
                "A6" to "Juli lampiño (sin pelo)",
                "A7" to "Lio",
                "A8" to "Mati acabando sobre una foto de sally (de cars)",
                "A9" to "Elegí a uno del grupo y dibujalo con una minusvalidad",
                "A10" to "Mati colgado en el baño de su casa después de que perdió boca",
                "A11" to "Todas las profesiones de las carreras que estudió Juli",
                "A12" to "Enzo en una oficina"

                ),
            "GRUPO B" to listOf(
                "B1" to "La hermana de Leo",
                "B2" to "La fantasía sexual del negro (Ema como el emperador)",
                "B3" to "El hijo down de Josué",
                "B4" to "El funeral de Iván",
                "B5" to "Leo en un trio con una gorda (hizo el sacrificio máximo)",
                "B6" to "Look at me Josue, I have the highground",
                "B7" to "Iván muerto por una botella de fernet (tomó un vaso nomás)",
                "B8" to "El culo de la amiga de la novia de Josué (según Josué)",
                "B9" to "Elegí a uno del grupo y dibujalo con una discapacidad",
                "B10" to "Iván tomando viagra",
                "B11" to "Leo con modorra"

                ),
            "GRUPO C" to listOf(
                "C1" to "Pablo presidente",
                "C2" to "Iván en un bar gay",
                "C3" to "Joaco inculpado de un femicidio (o Joaco femicida, depende de vos)",
                "C4" to "Gusti casándose con Pablo",
                "C5" to "Pablo fajando a su mujer porque perdio boca"
            ),
            "GENERAL" to listOf(
                "G1" to "Messi en pelotas comiendo una barrita de cereal",
                "G2" to "Hitler disfrazado de conejo sexy",
                "G3" to "Mia khalifa",
                "G4" to "Bertolo (Jugador de river)",
                "G5" to "Sandez (Jugador de boca)",
                "G6" to "Milei cogiendo con su hermana",
                "G7" to "(Elegí a alguien del público) teniendo un orgasmo",
                "G8" to "Culo pijeado",
                "G9" to "(Alguien del público con impotencia)",
                "G10" to "Esperma de caballo",
                "G11" to "Sexo con un caballo",
                "G12" to "Orgia Trans",
                "G13" to "Tetas acabadas"
            )
        ),
        "Suerte" to mapOf(
            "GENERAL" to listOf(
                "Proba tu suerte" to "Mala suerte",
                "Proba tu suerte" to "Buena suerte"
            )
        )
    )
}